server:
  port: 8001
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/test?useUnicode=true&serverTimezone=UTC&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root